// <auto-generated />
using System;
using MaestroNotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaestroNotes.Migrations
{
    [DbContext(typeof(MusicContext))]
    [Migration("20240715184851_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MaestroNotes.Data.MusicRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bewertung1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dirigent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Komponist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Orchester")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Solist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Spielsaison")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Werk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MusicRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
